[package]
name = "password_manager"
version = "0.1.0"
edition = "2021"

[dependencies]
sodiumoxide = "0.2"        
rocksdb = "0.22.0"         
tui = "0.19.0"             
crossterm = "0.27.0"       
x11-rs = "0.9"       
wayland-client = "0.31.5"  
reqwest = "0.12.5"         
